# Fixed point values
DECIMAL_POS = 10
FIXED_POINT_SIZE_BITS = 32
FIXED_POINT_SIZE_BYTES = 4

# Shader core registers
NUM_LOCAL_REGS = 16
NUM_GLOBAL_REGS = 48
NUM_OUTBOX_REGS = 8
REGISTER_SIZE_BITS = 32
REGISTER_SIZE_BYTES = 4