import sys
import os
import argparse
from PIL import Image

# Usage: python obj and texture to binary dump for C programs

def parse_obj(path, obj_scale=1.0, norm_scale=1.0, textLenX = 0, textLenY = 0):
    positions = []
    texcoords = []
    normals = []

    unique_vertices = {}
    final_vertices = []
    final_triangles = []

    if not os.path.exists(path):
        print(f"Error: File not found.")
        return None, None
    
    with open(path, 'r') as f:
        for line in f:
            tokens = line.split()
            if not tokens:
                continue

            if tokens[0] == 'v':
                positions.append([float(x) for x in tokens[1:4]])
            elif tokens[0] == 'vn':
                normals.append([float(x) for x in tokens[1:4]])
            elif tokens[0] == 'vt':
                texcoords.append([float(x) for x in tokens[1:3]])
            elif tokens[0] == 'f':
                v_defs = tokens[1:]

                current_face_indices = []

                for v in v_defs:
                    parts = v.split('/')
                    p_idx = int(parts[0]) - 1

                    t_idx = -1
                    n_idx = -1
                    if len(parts) > 1 and parts[1]:
                        temp_idx = int(parts[1]) - 1
                        if 0 <= temp_idx < len(texcoords):
                            t_idx = temp_idx
                    if len(parts) > 2 and parts[2]:
                        temp_idx = int(parts[2]) - 1
                        if 0 <= temp_idx < len(normals):
                            n_idx = temp_idx

                    key = (p_idx, t_idx)
                    if key not in unique_vertices:
                        unique_vertices[key] = len(final_vertices)
                        pos = positions[p_idx]
                        uv = texcoords[t_idx] if t_idx != -1 else [0.0, 0.0]
                        nv = normals[n_idx] if n_idx != -1 else [0.0, 0.0, 0.0]

                        final_vertices.append({
                            'x': pos[0] * obj_scale, 'y': pos[1] * obj_scale, 'z': pos[2] * obj_scale,
                            'tx': int(uv[0] * textLenX), 'ty': int((1.0 - uv[1]) * textLenY),
                            'nx': nv[0] * norm_scale, 'ny': nv[1] * norm_scale, 'nz': nv[2] * norm_scale
                        })
                    
                    current_face_indices.append(unique_vertices[key])
                
                tri = [
                    current_face_indices[0], 
                    current_face_indices[1],
                    current_face_indices[2]
                ]
                final_triangles.append(tri)

    return final_vertices, final_triangles

def write_c_header(vertices, triangles, output_path, textX, textY, pixels, name = "model"):
    with open(output_path, 'w') as f:
        f.write(f"/* Generated by obj_to_c.py */\n")
        f.write(f"/*Model Name: {name}*/\n\n")
        #structured as a header file with only the data and includes deemed necessary for now
        f.write(f"#include \"demos.h\"\n#include \"ugpu.h\"\n\n#include <stdint.h>\n#include <string.h>\n\n")
        #f.write(f"#define VERTEX_BUFFER_PK_ADDR (QSPI0_MEM_ADDR_DEFAULT + 0x90000)\n")
        #f.write(f"#define INDEX_BUFFER_PK_ADDR  (QSPI0_MEM_ADDR_DEFAULT + 0x80000)\n\n")

        f.write(f"#define {name.upper()}_VERTICES  ({len(vertices)})\n")
        f.write(f"#define {name.upper()}_TRIANGLES ({len(triangles)})\n")

        #Write Verts
        f.write(f"static const vertex_t {name}_vertices[{name.upper()}_VERTICES] = {{\n")
        for v in vertices:
            f.write("\t{\n")
            f.write(f"\t\t.x  = UGPU_FLOAT_TO_FIXED({v['x']}),\n")
            f.write(f"\t\t.y  = UGPU_FLOAT_TO_FIXED({v['y']}),\n")
            f.write(f"\t\t.z  = UGPU_FLOAT_TO_FIXED({v['z']}),\n")
            f.write(f"\t\t.tx = UGPU_FLOAT_TO_FIXED({v['tx']}),\n")
            f.write(f"\t\t.ty = UGPU_FLOAT_TO_FIXED({v['ty']}),\n")
            f.write(f"\t\t.nx = UGPU_FLOAT_TO_FIXED({v['nx']}),\n")
            f.write(f"\t\t.ny = UGPU_FLOAT_TO_FIXED({v['ny']}),\n")
            f.write(f"\t\t.nz = UGPU_FLOAT_TO_FIXED({v['nz']}),\n")
            f.write("\t},\n")
        f.write("};\n\n")

        #Triangle Write
        f.write(f"static const triangle_t {name}_triangles[{name.upper()}_TRIANGLES] = {{\n")
        for t in triangles:
            f.write(f"\t{{ {t[0]}, {t[1]}, {t[2]} }},\n")
        f.write("};\n")

        if(pixels != 0):
            f.write(f"#define {name.upper()}_SIZE_X ({textX})\n")
            f.write(f"#define {name.upper()}_SIZE_Y ({textY})\n")

            f.write(f"static const uint8_t {name}_t[] = {{\n")
            for i, (r, g, b) in enumerate(pixels):
                val_8bit = (b & 0b11000000) | ((g & 0b11100000) >> 2) | ((r & 0b11100000) >> 5);

                hex_val = format(val_8bit, '02x')
                f.write(f"0x{hex_val}, ")
                if(i % 15 == 0):
                    f.write("\n")

            f.write("\n};")

def jpg_to_rgb332(image_path):
    if not os.path.exists(image_path):
        print("Error: Image Not Found")
        return
    
    img = Image.open(image_path).convert('RGB')

    width, height = img.size

    pixels = list(img.getdata())

    return width, height, pixels

def main():
    parser = argparse.ArgumentParser(prog='Obj_to_C', description='Takes obj files and converts them into C structs defined in demos.h')
    parser.add_argument("input", help="Path to .obj file being converted")
    parser.add_argument("-o", "--output", help="Specify path to output file (defaults to input_name.h)")
    parser.add_argument("-s", "--scale", type=float, default=1.0, help="Scale Image Coordinates by this (default is 1.0)")
    parser.add_argument("-i", "--image", help="Path to .jpg file to dump")
    parser.add_argument("-ns", "--normscl", type=float, default=1.0, help="Scale Normal Values By This")
    
    args = parser.parse_all() if hasattr(parser, 'parse_all') else parser.parse_args()

    base_name = os.path.splitext(os.path.basename(args.input))[0]
    output_file = args.output if args.output else f"{base_name}.h"

    textX = 0
    textY = 0
    pixels = 0

    if args.image:
        print("Adding image to files")
        textX, textY, pixels = jpg_to_rgb332(args.image)

    print(f"Reading {args.input}...\n")
    verts, tris = parse_obj(args.input, args.scale, args.normscl, textX, textY)

    if verts:
        write_c_header(verts, tris, output_file, textX, textY, pixels, base_name)
        print(f"Done! Created '{output_file}' with {len(verts)} vertices and {len(tris)} triangles\n")
    else:
        print("Failed to parse OBJ.")

if __name__ == "__main__":
    main()
