###############################################################################
# Created by write_sdc
# Sat May  2 20:55:54 2026
###############################################################################
current_design core_busarb_m
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name clk_i -period 20.0000 [get_ports {clk_i}]
set_clock_transition 0.1500 [get_clocks {clk_i}]
set_clock_uncertainty 0.2500 clk_i
set_propagated_clock [get_clocks {clk_i}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[0]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[100]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[101]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[102]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[103]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[104]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[105]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[106]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[107]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[108]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[109]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[10]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[110]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[111]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[112]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[113]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[114]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[115]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[116]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[117]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[118]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[119]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[11]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[120]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[121]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[122]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[123]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[124]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[125]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[126]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[127]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[128]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[129]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[12]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[130]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[131]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[132]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[133]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[134]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[135]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[136]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[137]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[138]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[139]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[13]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[140]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[141]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[142]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[143]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[144]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[145]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[146]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[147]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[148]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[149]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[14]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[150]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[151]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[152]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[153]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[154]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[155]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[156]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[157]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[158]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[159]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[15]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[160]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[161]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[162]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[163]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[164]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[165]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[166]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[167]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[168]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[169]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[16]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[170]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[171]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[172]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[173]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[174]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[175]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[176]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[177]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[178]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[179]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[17]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[180]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[181]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[182]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[183]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[184]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[185]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[186]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[187]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[188]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[189]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[18]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[190]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[191]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[192]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[193]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[194]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[195]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[196]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[197]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[198]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[199]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[19]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[1]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[200]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[201]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[202]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[203]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[204]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[205]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[206]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[20]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[21]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[22]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[23]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[24]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[25]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[26]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[27]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[28]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[29]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[2]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[30]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[31]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[32]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[33]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[34]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[35]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[36]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[37]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[38]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[39]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[3]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[40]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[41]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[42]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[43]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[44]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[45]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[46]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[47]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[48]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[49]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[4]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[50]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[51]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[52]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[53]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[54]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[55]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[56]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[57]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[58]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[59]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[5]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[60]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[61]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[62]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[63]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[64]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[65]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[66]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[67]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[68]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[69]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[6]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[70]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[71]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[72]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[73]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[74]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[75]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[76]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[77]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[78]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[79]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[7]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[80]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[81]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[82]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[83]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[84]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[85]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[86]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[87]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[88]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[89]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[8]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[90]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[91]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[92]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[93]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[94]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[95]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[96]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[97]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[98]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[99]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_i[9]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {nrst_i}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_i[0]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_i[10]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_i[11]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_i[12]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_i[13]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_i[14]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_i[15]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_i[16]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_i[17]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_i[18]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_i[19]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_i[1]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_i[20]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_i[21]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_i[22]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_i[23]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_i[24]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_i[25]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_i[26]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_i[27]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_i[28]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_i[29]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_i[2]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_i[30]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_i[31]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_i[32]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_i[33]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_i[3]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_i[4]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_i[5]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_i[6]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_i[7]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_i[8]}]
set_input_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_i[9]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[0]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[100]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[101]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[10]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[11]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[12]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[13]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[14]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[15]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[16]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[17]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[18]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[19]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[1]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[20]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[21]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[22]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[23]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[24]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[25]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[26]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[27]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[28]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[29]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[2]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[30]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[31]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[32]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[33]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[34]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[35]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[36]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[37]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[38]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[39]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[3]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[40]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[41]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[42]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[43]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[44]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[45]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[46]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[47]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[48]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[49]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[4]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[50]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[51]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[52]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[53]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[54]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[55]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[56]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[57]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[58]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[59]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[5]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[60]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[61]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[62]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[63]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[64]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[65]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[66]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[67]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[68]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[69]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[6]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[70]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[71]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[72]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[73]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[74]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[75]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[76]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[77]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[78]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[79]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[7]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[80]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[81]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[82]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[83]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[84]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[85]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[86]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[87]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[88]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[89]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[8]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[90]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[91]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[92]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[93]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[94]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[95]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[96]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[97]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[98]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[99]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {mports_o[9]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[0]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[10]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[11]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[12]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[13]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[14]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[15]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[16]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[17]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[18]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[19]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[1]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[20]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[21]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[22]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[23]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[24]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[25]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[26]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[27]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[28]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[29]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[2]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[30]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[31]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[32]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[33]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[34]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[35]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[36]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[37]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[38]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[39]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[3]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[40]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[41]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[42]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[43]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[44]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[45]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[46]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[47]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[48]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[49]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[4]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[50]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[51]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[52]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[53]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[54]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[55]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[56]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[57]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[58]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[59]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[5]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[60]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[61]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[62]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[63]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[64]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[65]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[66]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[67]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[68]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[6]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[7]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[8]}]
set_output_delay 4.0000 -clock [get_clocks {clk_i}] -add_delay [get_ports {sports_o[9]}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0334 [get_ports {mports_o[101]}]
set_load -pin_load 0.0334 [get_ports {mports_o[100]}]
set_load -pin_load 0.0334 [get_ports {mports_o[99]}]
set_load -pin_load 0.0334 [get_ports {mports_o[98]}]
set_load -pin_load 0.0334 [get_ports {mports_o[97]}]
set_load -pin_load 0.0334 [get_ports {mports_o[96]}]
set_load -pin_load 0.0334 [get_ports {mports_o[95]}]
set_load -pin_load 0.0334 [get_ports {mports_o[94]}]
set_load -pin_load 0.0334 [get_ports {mports_o[93]}]
set_load -pin_load 0.0334 [get_ports {mports_o[92]}]
set_load -pin_load 0.0334 [get_ports {mports_o[91]}]
set_load -pin_load 0.0334 [get_ports {mports_o[90]}]
set_load -pin_load 0.0334 [get_ports {mports_o[89]}]
set_load -pin_load 0.0334 [get_ports {mports_o[88]}]
set_load -pin_load 0.0334 [get_ports {mports_o[87]}]
set_load -pin_load 0.0334 [get_ports {mports_o[86]}]
set_load -pin_load 0.0334 [get_ports {mports_o[85]}]
set_load -pin_load 0.0334 [get_ports {mports_o[84]}]
set_load -pin_load 0.0334 [get_ports {mports_o[83]}]
set_load -pin_load 0.0334 [get_ports {mports_o[82]}]
set_load -pin_load 0.0334 [get_ports {mports_o[81]}]
set_load -pin_load 0.0334 [get_ports {mports_o[80]}]
set_load -pin_load 0.0334 [get_ports {mports_o[79]}]
set_load -pin_load 0.0334 [get_ports {mports_o[78]}]
set_load -pin_load 0.0334 [get_ports {mports_o[77]}]
set_load -pin_load 0.0334 [get_ports {mports_o[76]}]
set_load -pin_load 0.0334 [get_ports {mports_o[75]}]
set_load -pin_load 0.0334 [get_ports {mports_o[74]}]
set_load -pin_load 0.0334 [get_ports {mports_o[73]}]
set_load -pin_load 0.0334 [get_ports {mports_o[72]}]
set_load -pin_load 0.0334 [get_ports {mports_o[71]}]
set_load -pin_load 0.0334 [get_ports {mports_o[70]}]
set_load -pin_load 0.0334 [get_ports {mports_o[69]}]
set_load -pin_load 0.0334 [get_ports {mports_o[68]}]
set_load -pin_load 0.0334 [get_ports {mports_o[67]}]
set_load -pin_load 0.0334 [get_ports {mports_o[66]}]
set_load -pin_load 0.0334 [get_ports {mports_o[65]}]
set_load -pin_load 0.0334 [get_ports {mports_o[64]}]
set_load -pin_load 0.0334 [get_ports {mports_o[63]}]
set_load -pin_load 0.0334 [get_ports {mports_o[62]}]
set_load -pin_load 0.0334 [get_ports {mports_o[61]}]
set_load -pin_load 0.0334 [get_ports {mports_o[60]}]
set_load -pin_load 0.0334 [get_ports {mports_o[59]}]
set_load -pin_load 0.0334 [get_ports {mports_o[58]}]
set_load -pin_load 0.0334 [get_ports {mports_o[57]}]
set_load -pin_load 0.0334 [get_ports {mports_o[56]}]
set_load -pin_load 0.0334 [get_ports {mports_o[55]}]
set_load -pin_load 0.0334 [get_ports {mports_o[54]}]
set_load -pin_load 0.0334 [get_ports {mports_o[53]}]
set_load -pin_load 0.0334 [get_ports {mports_o[52]}]
set_load -pin_load 0.0334 [get_ports {mports_o[51]}]
set_load -pin_load 0.0334 [get_ports {mports_o[50]}]
set_load -pin_load 0.0334 [get_ports {mports_o[49]}]
set_load -pin_load 0.0334 [get_ports {mports_o[48]}]
set_load -pin_load 0.0334 [get_ports {mports_o[47]}]
set_load -pin_load 0.0334 [get_ports {mports_o[46]}]
set_load -pin_load 0.0334 [get_ports {mports_o[45]}]
set_load -pin_load 0.0334 [get_ports {mports_o[44]}]
set_load -pin_load 0.0334 [get_ports {mports_o[43]}]
set_load -pin_load 0.0334 [get_ports {mports_o[42]}]
set_load -pin_load 0.0334 [get_ports {mports_o[41]}]
set_load -pin_load 0.0334 [get_ports {mports_o[40]}]
set_load -pin_load 0.0334 [get_ports {mports_o[39]}]
set_load -pin_load 0.0334 [get_ports {mports_o[38]}]
set_load -pin_load 0.0334 [get_ports {mports_o[37]}]
set_load -pin_load 0.0334 [get_ports {mports_o[36]}]
set_load -pin_load 0.0334 [get_ports {mports_o[35]}]
set_load -pin_load 0.0334 [get_ports {mports_o[34]}]
set_load -pin_load 0.0334 [get_ports {mports_o[33]}]
set_load -pin_load 0.0334 [get_ports {mports_o[32]}]
set_load -pin_load 0.0334 [get_ports {mports_o[31]}]
set_load -pin_load 0.0334 [get_ports {mports_o[30]}]
set_load -pin_load 0.0334 [get_ports {mports_o[29]}]
set_load -pin_load 0.0334 [get_ports {mports_o[28]}]
set_load -pin_load 0.0334 [get_ports {mports_o[27]}]
set_load -pin_load 0.0334 [get_ports {mports_o[26]}]
set_load -pin_load 0.0334 [get_ports {mports_o[25]}]
set_load -pin_load 0.0334 [get_ports {mports_o[24]}]
set_load -pin_load 0.0334 [get_ports {mports_o[23]}]
set_load -pin_load 0.0334 [get_ports {mports_o[22]}]
set_load -pin_load 0.0334 [get_ports {mports_o[21]}]
set_load -pin_load 0.0334 [get_ports {mports_o[20]}]
set_load -pin_load 0.0334 [get_ports {mports_o[19]}]
set_load -pin_load 0.0334 [get_ports {mports_o[18]}]
set_load -pin_load 0.0334 [get_ports {mports_o[17]}]
set_load -pin_load 0.0334 [get_ports {mports_o[16]}]
set_load -pin_load 0.0334 [get_ports {mports_o[15]}]
set_load -pin_load 0.0334 [get_ports {mports_o[14]}]
set_load -pin_load 0.0334 [get_ports {mports_o[13]}]
set_load -pin_load 0.0334 [get_ports {mports_o[12]}]
set_load -pin_load 0.0334 [get_ports {mports_o[11]}]
set_load -pin_load 0.0334 [get_ports {mports_o[10]}]
set_load -pin_load 0.0334 [get_ports {mports_o[9]}]
set_load -pin_load 0.0334 [get_ports {mports_o[8]}]
set_load -pin_load 0.0334 [get_ports {mports_o[7]}]
set_load -pin_load 0.0334 [get_ports {mports_o[6]}]
set_load -pin_load 0.0334 [get_ports {mports_o[5]}]
set_load -pin_load 0.0334 [get_ports {mports_o[4]}]
set_load -pin_load 0.0334 [get_ports {mports_o[3]}]
set_load -pin_load 0.0334 [get_ports {mports_o[2]}]
set_load -pin_load 0.0334 [get_ports {mports_o[1]}]
set_load -pin_load 0.0334 [get_ports {mports_o[0]}]
set_load -pin_load 0.0334 [get_ports {sports_o[68]}]
set_load -pin_load 0.0334 [get_ports {sports_o[67]}]
set_load -pin_load 0.0334 [get_ports {sports_o[66]}]
set_load -pin_load 0.0334 [get_ports {sports_o[65]}]
set_load -pin_load 0.0334 [get_ports {sports_o[64]}]
set_load -pin_load 0.0334 [get_ports {sports_o[63]}]
set_load -pin_load 0.0334 [get_ports {sports_o[62]}]
set_load -pin_load 0.0334 [get_ports {sports_o[61]}]
set_load -pin_load 0.0334 [get_ports {sports_o[60]}]
set_load -pin_load 0.0334 [get_ports {sports_o[59]}]
set_load -pin_load 0.0334 [get_ports {sports_o[58]}]
set_load -pin_load 0.0334 [get_ports {sports_o[57]}]
set_load -pin_load 0.0334 [get_ports {sports_o[56]}]
set_load -pin_load 0.0334 [get_ports {sports_o[55]}]
set_load -pin_load 0.0334 [get_ports {sports_o[54]}]
set_load -pin_load 0.0334 [get_ports {sports_o[53]}]
set_load -pin_load 0.0334 [get_ports {sports_o[52]}]
set_load -pin_load 0.0334 [get_ports {sports_o[51]}]
set_load -pin_load 0.0334 [get_ports {sports_o[50]}]
set_load -pin_load 0.0334 [get_ports {sports_o[49]}]
set_load -pin_load 0.0334 [get_ports {sports_o[48]}]
set_load -pin_load 0.0334 [get_ports {sports_o[47]}]
set_load -pin_load 0.0334 [get_ports {sports_o[46]}]
set_load -pin_load 0.0334 [get_ports {sports_o[45]}]
set_load -pin_load 0.0334 [get_ports {sports_o[44]}]
set_load -pin_load 0.0334 [get_ports {sports_o[43]}]
set_load -pin_load 0.0334 [get_ports {sports_o[42]}]
set_load -pin_load 0.0334 [get_ports {sports_o[41]}]
set_load -pin_load 0.0334 [get_ports {sports_o[40]}]
set_load -pin_load 0.0334 [get_ports {sports_o[39]}]
set_load -pin_load 0.0334 [get_ports {sports_o[38]}]
set_load -pin_load 0.0334 [get_ports {sports_o[37]}]
set_load -pin_load 0.0334 [get_ports {sports_o[36]}]
set_load -pin_load 0.0334 [get_ports {sports_o[35]}]
set_load -pin_load 0.0334 [get_ports {sports_o[34]}]
set_load -pin_load 0.0334 [get_ports {sports_o[33]}]
set_load -pin_load 0.0334 [get_ports {sports_o[32]}]
set_load -pin_load 0.0334 [get_ports {sports_o[31]}]
set_load -pin_load 0.0334 [get_ports {sports_o[30]}]
set_load -pin_load 0.0334 [get_ports {sports_o[29]}]
set_load -pin_load 0.0334 [get_ports {sports_o[28]}]
set_load -pin_load 0.0334 [get_ports {sports_o[27]}]
set_load -pin_load 0.0334 [get_ports {sports_o[26]}]
set_load -pin_load 0.0334 [get_ports {sports_o[25]}]
set_load -pin_load 0.0334 [get_ports {sports_o[24]}]
set_load -pin_load 0.0334 [get_ports {sports_o[23]}]
set_load -pin_load 0.0334 [get_ports {sports_o[22]}]
set_load -pin_load 0.0334 [get_ports {sports_o[21]}]
set_load -pin_load 0.0334 [get_ports {sports_o[20]}]
set_load -pin_load 0.0334 [get_ports {sports_o[19]}]
set_load -pin_load 0.0334 [get_ports {sports_o[18]}]
set_load -pin_load 0.0334 [get_ports {sports_o[17]}]
set_load -pin_load 0.0334 [get_ports {sports_o[16]}]
set_load -pin_load 0.0334 [get_ports {sports_o[15]}]
set_load -pin_load 0.0334 [get_ports {sports_o[14]}]
set_load -pin_load 0.0334 [get_ports {sports_o[13]}]
set_load -pin_load 0.0334 [get_ports {sports_o[12]}]
set_load -pin_load 0.0334 [get_ports {sports_o[11]}]
set_load -pin_load 0.0334 [get_ports {sports_o[10]}]
set_load -pin_load 0.0334 [get_ports {sports_o[9]}]
set_load -pin_load 0.0334 [get_ports {sports_o[8]}]
set_load -pin_load 0.0334 [get_ports {sports_o[7]}]
set_load -pin_load 0.0334 [get_ports {sports_o[6]}]
set_load -pin_load 0.0334 [get_ports {sports_o[5]}]
set_load -pin_load 0.0334 [get_ports {sports_o[4]}]
set_load -pin_load 0.0334 [get_ports {sports_o[3]}]
set_load -pin_load 0.0334 [get_ports {sports_o[2]}]
set_load -pin_load 0.0334 [get_ports {sports_o[1]}]
set_load -pin_load 0.0334 [get_ports {sports_o[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {clk_i}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {nrst_i}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[206]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[205]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[204]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[203]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[202]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[201]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[200]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[199]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[198]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[197]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[196]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[195]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[194]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[193]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[192]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[191]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[190]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[189]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[188]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[187]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[186]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[185]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[184]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[183]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[182]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[181]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[180]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[179]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[178]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[177]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[176]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[175]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[174]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[173]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[172]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[171]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[170]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[169]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[168]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[167]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[166]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[165]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[164]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[163]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[162]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[161]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[160]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[159]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[158]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[157]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[156]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[155]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[154]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[153]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[152]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[151]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[150]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[149]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[148]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[147]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[146]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[145]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[144]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[143]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[142]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[141]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[140]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[139]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[138]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[137]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[136]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[135]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[134]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[133]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[132]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[131]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[130]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[129]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[128]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[127]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[126]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[125]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[124]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[123]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[122]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[121]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[120]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[119]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[118]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[117]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[116]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[115]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[114]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[113]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[112]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[111]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[110]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[109]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[108]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[107]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[106]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[105]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[104]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[103]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[102]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[101]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[100]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[99]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[98]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[97]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[96]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[95]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[94]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[93]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[92]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[91]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[90]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[89]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[88]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[87]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[86]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[85]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[84]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[83]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[82]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[81]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[80]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[79]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[78]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[77]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[76]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[75]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[74]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[73]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[72]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[71]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[70]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[69]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[68]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[67]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[66]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[65]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[64]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[63]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[62]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[61]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[60]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[59]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[58]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[57]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[56]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[55]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[54]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[53]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[52]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[51]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[50]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[49]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[48]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[47]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[46]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[45]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[44]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[43]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[42]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[41]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[40]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[39]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[38]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[37]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[36]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[35]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[34]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[33]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[32]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[31]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[30]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[29]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[28]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[27]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[26]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[25]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[24]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[23]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[22]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[21]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[20]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[19]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[18]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[17]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[16]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[15]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[14]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[13]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[12]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[11]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[10]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[9]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[8]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mports_i[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {sports_i[33]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {sports_i[32]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {sports_i[31]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {sports_i[30]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {sports_i[29]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {sports_i[28]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {sports_i[27]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {sports_i[26]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {sports_i[25]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {sports_i[24]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {sports_i[23]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {sports_i[22]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {sports_i[21]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {sports_i[20]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {sports_i[19]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {sports_i[18]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {sports_i[17]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {sports_i[16]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {sports_i[15]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {sports_i[14]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {sports_i[13]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {sports_i[12]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {sports_i[11]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {sports_i[10]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {sports_i[9]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {sports_i[8]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {sports_i[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {sports_i[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {sports_i[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {sports_i[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {sports_i[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {sports_i[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {sports_i[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {sports_i[0]}]
set_timing_derate -early 0.9500
set_timing_derate -late 1.0500
###############################################################################
# Design Rules
###############################################################################
set_max_transition 0.7500 [current_design]
set_max_fanout 10.0000 [current_design]
